definitions:
  models.Center:
    properties:
      center_name:
        type: string
      center_no:
        type: string
    type: object
  models.Vender:
    properties:
      sire_name:
        type: string
      sire_no:
        type: string
    type: object
  request.NyukaInputRequest:
    properties:
      center_no:
        type: string
      nyuka_begin:
        type: string
      nyuka_end:
        type: string
      sire_no:
        type: string
    type: object
  response.NyukaInputResponse:
    properties:
      count:
        type: integer
      orderNo_List:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
paths:
  /api/v1/Vender:
    get:
      consumes:
      - application/json
      description: Get vender details by ID
      parameters:
      - description: vender_no
        in: query
        name: vender_no
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Vender'
  /api/v1/center:
    get:
      consumes:
      - application/json
      description: Get center details by ID
      parameters:
      - description: center_no
        in: query
        name: center_no
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Center'
  /api/v1/nyuka/getcounts:
    post:
      consumes:
      - application/json
      parameters:
      - description: test
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.NyukaInputRequest'
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/response.NyukaInputResponse'
      summary: 获取未入荷条数
swagger: "2.0"
