// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-studying/app"
	"go-studying/api/router"
)

// Injectors from wire.go:

func InitServer() *app.Server {
	engine := app.NewGinEngine()
	client := app.InitSpannerDB()

	router.InitAccountRouter(client,engine)
	router.InitCenterRouter(client,engine)

	// iAccountRepo := repo.NewSpannerAccountRepository(client)
	// iAccountService := service.NewAccountService(iAccountRepo)
	// accountHandler := handler.NewAccountHandlers(iAccountService)
	// routerRouter := router.NewRouter(accountHandler)
	// server := app.NewServer(engine, routerRouter)
	server := app.NewServer(engine)
	return server
}
