// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-studying/api/handler"
	"go-studying/api/router"
	"go-studying/app"
	"go-studying/repo"
	"go-studying/service"
)

// Injectors from wire.go:

func InitServer() *app.Server {
	engine := app.NewGinEngine()
	client := app.InitSpannerDB()
	iAccountRepo := repo.NewSpannerAccountRepository(client)
	iAccountService := service.NewAccountService(iAccountRepo)
	accountHandler := handler.NewAccountHandlers(iAccountService)
	accountRouter := router.NewAccountRouter(accountHandler)
	iCenterRepo := repo.NewSpannerCenterRepository(client)
	iCenterService := service.NewCenterService(iCenterRepo)
	centerHandler := handler.NewCenterHandlers(iCenterService)
	centerRouter := router.NewCenterRouter(centerHandler)
	server := app.NewServer(engine, accountRouter, centerRouter)
	return server
}
